#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

from zhusuan import distributions
from zhusuan.model.base import StochasticTensor
from zhusuan.model.utils import overload_name_param


__all__ = [
    'Normal',
    'Bernoulli',
    'Categorical',
    'OnehotCategorical',
    'Discrete',
    'OnehotDiscrete',
    'Uniform',
    'Gamma',
    'Beta',
    'Poisson',
    'Binomial',
    'InverseGamma',
    'Laplace',
    'Multinomial',
    'Dirichlet',
    'BinConcrete',
    'ExpConcrete',
    'Concrete',
]


class Normal(StochasticTensor):
    """
    The class of univariate Normal `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    .. warning::

         The order of arguments `logstd`/`std` will change to `std`/`logstd`
         in the coming version.

    :param mean: A `float` Tensor. The mean of the Normal distribution.
        Should be broadcastable to match `logstd`.
    :param logstd: A `float` Tensor. The log standard deviation of the Normal
        distribution. Should be broadcastable to match `mean`.
    :param std: A `float` Tensor. The standard deviation of the Normal
        distribution. Should be positive and broadcastable to match `mean`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Normal')
    def __init__(self,
                 mean=0.,
                 logstd=None,
                 std=None,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        norm = distributions.Normal(
            mean,
            logstd=logstd,
            std=std,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics
        )
        super(Normal, self).__init__(
            norm, n_samples, name=name, observed=observed)


class Bernoulli(StochasticTensor):
    """
    The class of univariate Bernoulli `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param logits: A `float` Tensor. The log-odds of probabilities of being 1.

        .. math:: \\mathrm{logits} = \\log \\frac{p}{1 - p}

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Bernoulli')
    def __init__(self,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 observed=None,
                 name=None):
        bernoulli = distributions.Bernoulli(
            logits,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
        )
        super(Bernoulli, self).__init__(
            bernoulli, n_samples, name=name, observed=observed)


class Categorical(StochasticTensor):
    """
    The class of univariate Categorical `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param logits: A N-D (N >= 1) `float` Tensor of shape (...,
        n_categories). Each slice `[i, j,..., k, :]` represents the
        un-normalized log probabilities for all categories.

        .. math:: \\mathrm{logits} \\propto \\log p

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.

    A single sample is a (N-1)-D Tensor with `tf.int32` values in range
    [0, n_categories).
    """

    @overload_name_param('Categorical')
    def __init__(self,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 observed=None,
                 name=None):
        cat = distributions.Categorical(
            logits,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
        )
        super(Categorical, self).__init__(
            cat, n_samples, name=name, observed=observed)


Discrete = Categorical


class Uniform(StochasticTensor):
    """
    The class of univariate Uniform `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param minval: A `float` Tensor. The lower bound on the range of the
        uniform distribution. Should be broadcastable to match `maxval`.
    :param maxval: A `float` Tensor. The upper bound on the range of the
        uniform distribution. Should be element-wise bigger than `minval`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Uniform')
    def __init__(self,
                 minval=0.,
                 maxval=1.,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        uniform = distributions.Uniform(
            minval,
            maxval,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics
        )
        super(Uniform, self).__init__(
            uniform, n_samples, name=name, observed=observed)


class Gamma(StochasticTensor):
    """
    The class of univariate Gamma `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param alpha: A `float` Tensor. The shape parameter of the Gamma
        distribution. Should be positive and broadcastable to match `beta`.
    :param beta: A `float` Tensor. The inverse scale parameter of the Gamma
        distribution. Should be positive and broadcastable to match `alpha`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Gamma')
    def __init__(self,
                 alpha,
                 beta,
                 n_samples=None,
                 group_event_ndims=0,
                 check_numerics=False,
                 observed=None,
                 name=None):
        gamma = distributions.Gamma(
            alpha,
            beta,
            group_event_ndims=group_event_ndims,
            check_numerics=check_numerics
        )
        super(Gamma, self).__init__(
            gamma, n_samples, name=name, observed=observed)


class Beta(StochasticTensor):
    """
    The class of univariate Beta `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param alpha: A `float` Tensor. One of the two shape parameters of the
        Beta distribution. Should be positive and broadcastable to match
        `beta`.
    :param beta: A `float` Tensor. One of the two shape parameters of the
        Beta distribution. Should be positive and broadcastable to match
        `alpha`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Beta')
    def __init__(self,
                 alpha,
                 beta,
                 n_samples=None,
                 group_event_ndims=0,
                 check_numerics=False,
                 observed=None,
                 name=None):
        beta = distributions.Beta(
            alpha,
            beta,
            group_event_ndims=group_event_ndims,
            check_numerics=check_numerics
        )
        super(Beta, self).__init__(
            beta, n_samples, name=name, observed=observed)


class Poisson(StochasticTensor):
    """
    The class of univariate Poisson `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param rate: A `float` Tensor. The rate parameter of Poisson
        distribution. Must be positive.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Poisson')
    def __init__(self,
                 rate,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 check_numerics=False,
                 observed=None,
                 name=None):
        poisson = distributions.Poisson(
            rate,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
            check_numerics=check_numerics
        )
        super(Poisson, self).__init__(
            poisson, n_samples, name=name, observed=observed)


class Binomial(StochasticTensor):
    """
    The class of univariate Binomial `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param logits: A `float` Tensor. The log-odds of probabilities.

        .. math:: \\mathrm{logits} = \\log \\frac{p}{1 - p}

    :param n_experiments: A 0-D `int32` Tensor. The number of experiments
        for each sample.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Binomial')
    def __init__(self,
                 logits,
                 n_experiments,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 check_numerics=False,
                 observed=None,
                 name=None):
        binomial = distributions.Binomial(
            logits,
            n_experiments,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
            check_numerics=check_numerics
        )
        super(Binomial, self).__init__(
            binomial, n_samples, name=name, observed=observed)


class Multinomial(StochasticTensor):
    """
    The class of Multinomial `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param logits: A N-D (N >= 1) `float` Tensor of shape (...,
        n_categories). Each slice `[i, j, ..., k, :]` represents the
        un-normalized log probabilities for all categories.

        .. math:: \\mathrm{logits} \\propto \\log p

    :param n_experiments: A 0-D `int32` Tensor. The number of experiments
        for each sample.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.

    A single sample is a N-D Tensor with the same shape as logits. Each slice
    `[i, j, ..., k, :]` is a vector of counts for all categories.
    """

    @overload_name_param('Multinomial')
    def __init__(self,
                 logits,
                 n_experiments,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 observed=None,
                 name=None):
        multinomial = distributions.Multinomial(
            logits,
            n_experiments,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
        )
        super(Multinomial, self).__init__(
            multinomial, n_samples, name=name, observed=observed)


class OnehotCategorical(StochasticTensor):
    """
    The class of one-hot Categorical `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param logits: A N-D (N >= 1) `float` Tensor of shape (...,
        n_categories). Each slice `[i, j, ..., k, :]` represents the
        un-normalized log probabilities for all categories.

        .. math:: \\mathrm{logits} \\propto \\log p

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param dtype: The value type of this `StochasticTensor`.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.

    A single sample is a N-D Tensor with the same shape as logits. Each slice
    `[i, j, ..., k, :]` is a one-hot vector of the selected category.
    """

    @overload_name_param('OnehotCategorical')
    def __init__(self,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 dtype=None,
                 observed=None,
                 name=None):
        onehot_cat = distributions.OnehotCategorical(
            logits,
            group_event_ndims=group_event_ndims,
            dtype=dtype,
        )
        super(OnehotCategorical, self).__init__(
            onehot_cat, n_samples, name=name, observed=observed)


OnehotDiscrete = OnehotCategorical


class Dirichlet(StochasticTensor):
    """
    The class of Dirichlet `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param alpha: A N-D (N >= 1) `float` Tensor of shape (..., n_categories).
        Each slice `[i, j, ..., k, :]` represents the concentration parameter
        of a Dirichlet distribution. Should be positive.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.

    A single sample is a N-D Tensor with the same shape as alpha. Each slice
    `[i, j, ..., k, :]` of the sample is a vector of probabilities of a
    Categorical distribution `[x_1, x_2, ... ]`, which lies on the simplex

    .. math:: \\sum_{i} x_i = 1, 0 < x_i < 1

    """

    @overload_name_param('Dirichlet')
    def __init__(self,
                 alpha,
                 n_samples=None,
                 group_event_ndims=0,
                 check_numerics=False,
                 observed=None,
                 name=None):
        dirichlet = distributions.Dirichlet(
            alpha,
            group_event_ndims=group_event_ndims,
            check_numerics=check_numerics,
        )
        super(Dirichlet, self).__init__(
            dirichlet, n_samples, name=name, observed=observed)


class InverseGamma(StochasticTensor):
    """
    The class of univariate InverseGamma `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param alpha: A `float` Tensor. The shape parameter of the InverseGamma
        distribution. Should be positive and broadcastable to match `beta`.
    :param beta: A `float` Tensor. The scale parameter of the InverseGamma
        distribution. Should be positive and broadcastable to match `alpha`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('InverseGamma')
    def __init__(self,
                 alpha,
                 beta,
                 n_samples=None,
                 group_event_ndims=0,
                 check_numerics=False,
                 observed=None,
                 name=None):
        inv_gamma = distributions.InverseGamma(
            alpha,
            beta,
            group_event_ndims=group_event_ndims,
            check_numerics=check_numerics,
        )
        super(InverseGamma, self).__init__(
            inv_gamma, n_samples, name=name, observed=observed)


class Laplace(StochasticTensor):
    """
    The class of univariate Laplace `StochasticTensor`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    :param loc: A `float` Tensor. The location parameter of the Laplace
        distribution. Should be broadcastable to match `scale`.
    :param scale: A `float` Tensor. The scale parameter of the Laplace
        distribution. Should be positive and broadcastable to match `loc`.
    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Laplace')
    def __init__(self,
                 loc,
                 scale,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        laplace = distributions.Laplace(
            loc,
            scale,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics,
        )
        super(Laplace, self).__init__(
            laplace, n_samples, name=name, observed=observed)


class BinConcrete(StochasticTensor):
    """
    The class of univariate BinConcrete `StochasticTensor` from
    (Maddison, 2016). It is the binary case of :class:`~Concrete`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    .. seealso::

        :class:`~Concrete` and :class:`~ExpConcrete`

    :param temperature: A 0-D `float` Tensor. The temperature of the relaxed
        distribution. The temperature should be positive.
    :param logits: A `float` Tensor. The log-odds of probabilities of being 1.

        .. math:: \\mathrm{logits} = \\log \\frac{p}{1 - p}

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('BinConcrete')
    def __init__(self,
                 temperature,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        bin_concrete = distributions.BinConcrete(
            temperature,
            logits,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics,
        )
        super(BinConcrete, self).__init__(
            bin_concrete, n_samples, name=name, observed=observed)


class ExpConcrete(StochasticTensor):
    """
    The class of ExpConcrete `StochasticTensor` from (Maddison, 2016),
    transformed from :class:`~Concrete` by taking logarithm.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    .. seealso::

        :class:`~BinConcrete` and :class:`~Concrete`

    :param temperature: A 0-D `float` Tensor. The temperature of the relaxed
        distribution. The temperature should be positive.
    :param logits: A N-D (N >= 1) `float` Tensor of shape (...,
        n_categories). Each slice `[i, j, ..., k, :]` represents the
        un-normalized log probabilities for all categories.

        .. math:: \\mathrm{logits} \\propto \\log p

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('ExpConcrete')
    def __init__(self,
                 temperature,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        exp_concrete = distributions.ExpConcrete(
            temperature,
            logits,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics
        )
        super(ExpConcrete, self).__init__(
            exp_concrete, n_samples, name=name, observed=observed)


class Concrete(StochasticTensor):
    """
    The class of Concrete `StochasticTensor` from (Maddison, 2016), served as
    the continuous relaxation of the :class:`~OnehotCategorical`.
    See :class:`~zhusuan.model.base.StochasticTensor` for details.

    .. seealso::

        :class:`~BinConcrete` and :class:`~ExpConcrete`

    :param temperature: A 0-D `float` Tensor. The temperature of the relaxed
        distribution. The temperature should be positive.
    :param logits: A N-D (N >= 1) `float` Tensor of shape (...,
        n_categories). Each slice `[i, j, ..., k, :]` represents the
        un-normalized log probabilities for all categories.

        .. math:: \\mathrm{logits} \\propto \\log p

    :param n_samples: A 0-D `int32` Tensor or None. Number of samples
        generated by this `StochasticTensor`.
    :param group_event_ndims: A 0-D `int32` Tensor representing the number of
        dimensions in `batch_shape` (counted from the end) that are grouped
        into a single event, so that their probabilities are calculated
        together. Default is 0, which means a single value is an event.
        See :class:`~zhusuan.distributions.base.Distribution` for more detailed
        explanation.
    :param is_reparameterized: A Bool. If True, gradients on samples from this
        `StochasticTensor` are allowed to propagate into inputs, using the
        reparametrization trick from (Kingma, 2013).
    :param check_numerics: Bool. Whether to check numeric issues.
    :param observed: A Tensor, which matches the shape of `distribution`.
        If specified, will be used as the value of this stochastic tensor,
        instead of sampling from the distribution. This argument will
        also overwrite the value provided via BayesianNet context.
    :param name: A string. The name of the stochastic tensor. If specified, and
        the stochastic tensor is created in a BayesianNet context, the tensor
        will be added into that BayesianNet. The name must be unique in a
        BayesianNet context.
    """

    @overload_name_param('Concrete')
    def __init__(self,
                 temperature,
                 logits,
                 n_samples=None,
                 group_event_ndims=0,
                 is_reparameterized=True,
                 check_numerics=False,
                 observed=None,
                 name=None):
        concrete = distributions.Concrete(
            temperature,
            logits,
            group_event_ndims=group_event_ndims,
            is_reparameterized=is_reparameterized,
            check_numerics=check_numerics
        )
        super(Concrete, self).__init__(
            concrete, n_samples, name=name, observed=observed)
